services:
  - type: web
    name: nangulu-pos
    env: python
    pythonVersion: "3.11.7"
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: gunicorn app.main:app --workers 2 --worker-class uvicorn.workers.UvicornWorker --bind 0.0.0.0:$PORT
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: SECRET_KEY
        generateValue: true
      - key: PYTHON_VERSION
        value: 3.11.7
      - key: RENDER
        value: true
    healthCheckPath: /health
    autoDeploy: true
